version: '2'
services:
    helloserver:
        #container_name: helloserver -- Remove container_name due to compose is going to launch several instances and it needs to have different names
        build:
            context: Hello_Server
            dockerfile: Dockerfile
        image: helloserver:latest
        ports:
            - 18000-18888:8080
        networks:
            - spring-cloud-network
    byeserver:
        # container_name: byeserver -- Remove container_name due to compose is going to launch several instances and it needs to have different names
        build:
            context: Bye_Server
            dockerfile: Dockerfile
        image: byeserver:latest
        ports:
            - 19000-19999:8081
        networks:
            - spring-cloud-network
networks:
    spring-cloud-network:
        driver: bridge